<?php

namespace LaravelForum;



class Discussion extends Model
{

    public function author() {

        return $this->belongsTo(User::class,'user_id');
    }

    public function replies(){
        return $this->hasMany(Reply::class);
    }


    /**
     * To override what laravel uses in route-model-binding
     *
     * @return mixed
     */

    public function getRouteKeyName()
    {

        return 'slug';
//        return parent::getRouteKeyName('slug'); // TODO: Change the autogenerated stub
    }


    public function bestReply(){

        return $this->belongsTo(Reply::class, 'reply_id');
    }


    public function markAsBestReply(Reply $reply) {
        $this->update([
            'reply_id' => $reply->id,
        ]);
    }
}
